version: "3"
services:
  influxdb_v2:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXD_HTTP_BIND_ADDRESS=:8086
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_center
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token

    command: influxd --reporting-disabled

  mosquitto:
    image: eclipse-mosquitto:2.0.10
    ports:
      - "1883:1883"
    volumes:
#      - $PWD/mosquitto:/mosquitto/
      - $PWD/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  telegraf:
    image: telegraf:latest
    volumes:
      - $PWD/config/telegraf.conf:/etc/telegraf/telegraf.conf

  iot_center:
    image: ghcr.io/bonitoo-io/iot-center-v2/iot-center:nightly
    ports:
      - "5000:5000"
    environment:
      - INFLUX_URL=http://192.168.1.75:8086
      - INFLUX_TOKEN=my-token
      - INFLUX_ORG=my-org
      - MQTT_TOPIC=iot_center
      - MQTT_URL=mqtt://mosquitto:1883
    depends_on:
      - mosquitto
      - influxdb_v2
      - telegraf
    volumes:
      - $PWD/config/data:/usr/src/data